### ISSUE TITLE
HACS Integration

### ISSUE THREAD

**Issue by auredor** [gieljnssns/buienalarm#4]
Hello,

Nice work.

Would it be possible to make this compenent available through HACS ?
So, the installation would be easier and we would be notified of any new release.

Thanks.

**Comment by gieljnssns** [comment]
I'm on a vacation right now. 
When I'm back, I will try to find some free time. 
It was already on my roadmap.

**Comment by gieljnssns** [comment]
You should find ```Buienalarm``` in HACS right now...
